[versions]
kotlin = "2.3.21"
spring-boot = "4.1.0"
spring-dependency-management = "1.1.7"
kotest = "6.2.3"
kotlin-logging = "7.0.3"
spring-boot-logbook = "4.0.4"

[plugins]
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinSpring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kotlinJpa = { id = "org.jetbrains.kotlin.plugin.jpa", version.ref = "kotlin" }
kotlinKapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }

springBoot = { id = "org.springframework.boot", version.ref = "spring-boot" }
springDependencyManagement = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }

[libraries]
kotestBom = { module = "io.kotest:kotest-bom", version.ref = "kotest" }
kotlinLogging = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "kotlin-logging" }
springBootLogbook = { module = "org.zalando:logbook-spring-boot-starter", version.ref = "spring-boot-logbook" }
