#!/usr/bin/env python3
from __future__ import annotations

import argparse
import os
import re
import tempfile
from collections import Counter
from dataclasses import dataclass
from datetime import date
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
REQUIREMENTS_DIR = ROOT / "docs" / "requirements"
INDEX_PATH = REQUIREMENTS_DIR / "index.md"
SUMMARY_START = "<!-- requirements-summary:start -->"
SUMMARY_END = "<!-- requirements-summary:end -->"

STATUS_ORDER = ("DRAFT", "ACCEPTED", "IMPLEMENTED", "VERIFIED", "DEFERRED", "REJECTED")
STAGE_INTENTS = {
    "MVP": "Basic source-layer reading and interpretation",
    "STAGE-2": "Manual sketches",
    "STAGE-3": "Spatial and derived analysis",
    "LATER": "Explicitly postponed capabilities",
}
PRIORITIES = {"MUST", "SHOULD", "COULD"}

REQUIREMENT_HEADING = re.compile(
    r"^## ([A-Z][A-Z0-9-]*-\d+) — (.+?)\s*$",
    flags=re.MULTILINE,
)
DOCUMENT_TITLE = re.compile(r"^# (.+?)\s*$", flags=re.MULTILINE)


@dataclass(frozen=True)
class Requirement:
    identifier: str
    title: str
    area: str
    area_file: str
    status: str
    priority: str
    stage: str


def metadata_value(section: str, label: str, source: Path) -> str:
    match = re.search(rf"^- {re.escape(label)}:\s*(.+?)\s*$", section, flags=re.MULTILINE)
    if not match:
        raise ValueError(f"{source}: requirement is missing '- {label}:'.")
    return match.group(1).strip().strip("`")


def parse_area_file(path: Path) -> list[Requirement]:
    text = path.read_text(encoding="utf-8")
    title_match = DOCUMENT_TITLE.search(text)
    if not title_match:
        raise ValueError(f"{path}: missing level-one application-area title.")
    area = title_match.group(1).removesuffix(" Requirements")

    headings = list(REQUIREMENT_HEADING.finditer(text))
    requirements: list[Requirement] = []
    for index, heading in enumerate(headings):
        end = headings[index + 1].start() if index + 1 < len(headings) else len(text)
        section = text[heading.end():end]
        status = metadata_value(section, "Status", path)
        priority = metadata_value(section, "Priority", path)
        stage = metadata_value(section, "Delivery stage", path)
        if status not in STATUS_ORDER:
            raise ValueError(f"{path}: {heading.group(1)} has unsupported status {status!r}.")
        if priority not in PRIORITIES:
            raise ValueError(f"{path}: {heading.group(1)} has unsupported priority {priority!r}.")
        if stage not in STAGE_INTENTS:
            raise ValueError(f"{path}: {heading.group(1)} has unsupported delivery stage {stage!r}.")
        requirements.append(Requirement(
            identifier=heading.group(1),
            title=heading.group(2),
            area=area,
            area_file=path.name,
            status=status,
            priority=priority,
            stage=stage,
        ))
    return requirements


def load_requirements(directory: Path = REQUIREMENTS_DIR) -> list[Requirement]:
    requirements: list[Requirement] = []
    for path in sorted(directory.glob("*.md")):
        if path.name != "index.md":
            requirements.extend(parse_area_file(path))

    identifiers = [requirement.identifier for requirement in requirements]
    duplicates = sorted(identifier for identifier, count in Counter(identifiers).items() if count > 1)
    if duplicates:
        raise ValueError(f"Duplicate requirement IDs: {', '.join(duplicates)}.")
    return requirements


def markdown_text(value: str) -> str:
    return value.replace("|", r"\|")


def render_summary(requirements: list[Requirement]) -> str:
    total = len(requirements)
    verified_total = sum(requirement.status == "VERIFIED" for requirement in requirements)
    lines = [
        "<!-- Generated by scripts/update_requirements_index.py. Do not edit these tables manually. -->",
        "",
        "## Application Area Summary",
        "",
        "| Application area | Total | Verified | Completion | Area file |",
        "| --- | ---: | ---: | ---: | --- |",
    ]

    by_area: dict[tuple[str, str], list[Requirement]] = {}
    for requirement in requirements:
        by_area.setdefault((requirement.area, requirement.area_file), []).append(requirement)
    for (area, area_file), area_requirements in sorted(
        by_area.items(), key=lambda item: item[0][0].casefold()
    ):
        area_total = len(area_requirements)
        area_verified = sum(requirement.status == "VERIFIED" for requirement in area_requirements)
        completion = round(area_verified * 100 / area_total)
        label = markdown_text(area)
        lines.append(
            f"| {label} | {area_total} | {area_verified} | {completion}% | "
            f"[{label}]({area_file}) |"
        )
    completion_total = round(verified_total * 100 / total) if total else 0
    lines.append(
        f"| **All areas** | **{total}** | **{verified_total}** | "
        f"**{completion_total}%** | |"
    )

    stage_counts = Counter(requirement.stage for requirement in requirements)
    stage_verified = Counter(
        requirement.stage for requirement in requirements if requirement.status == "VERIFIED"
    )
    lines.extend([
        "",
        "## Delivery-stage Summary",
        "",
        "| Stage | Intent | Total | Verified |",
        "| --- | --- | ---: | ---: |",
    ])
    for stage, intent in STAGE_INTENTS.items():
        lines.append(f"| `{stage}` | {intent} | {stage_counts[stage]} | {stage_verified[stage]} |")
    lines.append(f"| **All stages** | | **{total}** | **{verified_total}** |")

    status_counts = Counter(requirement.status for requirement in requirements)
    lines.extend([
        "",
        "## Status Summary",
        "",
        "| Status | Count |",
        "| --- | ---: |",
    ])
    for status in STATUS_ORDER:
        lines.append(f"| `{status}` | {status_counts[status]} |")
    lines.append(f"| **All statuses** | **{total}** |")
    return "\n".join(lines)


def replace_summary(index_text: str, summary: str) -> str:
    if index_text.count(SUMMARY_START) != 1 or index_text.count(SUMMARY_END) != 1:
        raise ValueError("Requirements index must contain exactly one generated-summary marker pair.")
    before, remainder = index_text.split(SUMMARY_START, 1)
    _, after = remainder.split(SUMMARY_END, 1)
    return f"{before}{SUMMARY_START}\n\n{summary.rstrip()}\n\n{SUMMARY_END}{after}"


def write_atomic(path: Path, content: str) -> None:
    with tempfile.NamedTemporaryFile(
        "w", encoding="utf-8", dir=path.parent, prefix=f".{path.name}-", delete=False
    ) as temporary:
        temporary.write(content)
        temporary_path = Path(temporary.name)
    try:
        os.replace(temporary_path, path)
    except OSError:
        temporary_path.unlink(missing_ok=True)
        raise


def update_index(*, check: bool = False, today: date | None = None) -> bool:
    requirements = load_requirements()
    original = INDEX_PATH.read_text(encoding="utf-8")
    updated = replace_summary(original, render_summary(requirements))
    if updated == original:
        return False
    if check:
        raise RuntimeError(
            "Requirements index is stale. Run ./scripts/update_requirements_index.py."
        )
    current_date = (today or date.today()).isoformat()
    updated, replacements = re.subn(
        r"^- Last updated: \d{4}-\d{2}-\d{2}\s*$",
        f"- Last updated: {current_date}",
        updated,
        count=1,
        flags=re.MULTILINE,
    )
    if replacements != 1:
        raise ValueError("Requirements index must contain one '- Last updated: YYYY-MM-DD' line.")
    write_atomic(INDEX_PATH, updated)
    return True


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Update aggregate requirement statistics in docs/requirements/index.md."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail without writing when the generated summary is stale",
    )
    args = parser.parse_args()
    try:
        changed = update_index(check=args.check)
    except (OSError, RuntimeError, ValueError) as error:
        parser.exit(1, f"error: {error}\n")
    if args.check:
        print("Requirements index is current.")
    elif changed:
        print(f"Updated {INDEX_PATH.relative_to(ROOT)}.")
    else:
        print("Requirements index was already current.")


if __name__ == "__main__":
    main()
